### ISSUE TITLE
1,000 UPM?

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/aref-ruqaa#2]
I'm curious why you're not using a 1,000 UPM? 

cf https://github.com/khaledhosny/aref-ruqaa/blob/master/tools/build.py#L10

**Comment by khaledhosny** [comment]
I have no preference either way, I just need to use the same em value for the two fonts when merging and I think scaling up is less likely to cause rounding errors than scaling down.

**Comment by davelab6** [comment]
I'd prefer 1,000 as larger isn't useful and increases filesize

**Comment by khaledhosny** [comment]
OK, I’m giving it a try. Since it done build time, it should be easy to change later.

**Comment by davelab6** [comment]
You could also use a 1024 upm for easy flawless scaling if it matters
